version: '3'
services:

  mariadb:
    image: "mariadb:10.3.9"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=secret-root-pw
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/docker.cnf
      - data:/var/lib/mysql

  redis-cache:
    image: redis:4.0.11-alpine
    volumes:
      - ./conf/redis_cache.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]

  redis-queue:
    image: redis:4.0.11-alpine
    volumes:
      - ./conf/redis_queue.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]

  redis-socketio:
    image: redis:4.0.11-alpine
    volumes:
      - ./conf/redis_socketio.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]

  erpnext:
    image: protometa/erpnext
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_ROOT_PASSWORD=secret-root-pw
      - ADMIN_PASSWORD=secret-admin-pw
      - DB_HOST=mariadb
      - REDIS_CACHE=redis://redis-cache:13000
      - REDIS_QUEUE=redis://redis-queue:11000
      - REDIS_SOCKETIO=redis://redis-socketio:12000
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    extra_hosts:
      - "site1.local:127.0.0.1"
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb

volumes:
  data:
  sites:
